routes/web.php
<?php
use Illuminate\Support\Facades\Input;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
   // return view('welcome');
//});

Route::get('/', '\App\Http\Controllers\Auth\LoginController@showLoginForm');
Auth::routes();


Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware' => ['auth']], function(){
    Route::group(['middleware'=>['role:Администратор|Заведующий Складом']],function(){

    Route::get('/reports',[
        'as'=>'reports.index',
        'uses'=>'ReportController@index'
    ]);
        Route::get('logout/', 'DashboardController@logout')->name('admin.logout');
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
        //Route::get('profile', 'DashboardController@profile')->name('profile');
        Route::post('/stocks/{id}',[
            'as' => 'stocks.add',
            'uses' => 'StockController@add'
        ]);


        Route::resource('stocks','StockController');
        Route::resource('finalcategories','FinalcategoryController');
        Route::resource('lines','LineController');
        Route::resource('equiptments', 'EquiptmentController');
        Route::resource('equiptstatuses', 'EquiptstatusController');
        Route::resource('subcategories','SubcategoryController');
        Route::resource('categories','CategoryController');
        Route::resource('regions','RegionController');
        Route::resource('departments','DepartmentController');
        Route::resource('tollings','TollingController');
        Route::resource('roles','RoleController');
        Route::resource('warehouses','WarehouseController');
        Route::resource('users','UserController');
        Route::resource('permissions', 'PermissionController');



        Route::get('/information/create/ajax-state',function()
        {
            $cat_id = Input::get('category_id');
            $subcategories = \App\Subcategory::where('category_id','=',$cat_id)->get();
            return Response::json($subcategories);

        });

        Route::get('/information/create/ajax',function()
        {
            $region_id = Input::get('region_id');
            $warehouses = \App\Warehouse::where('region_id','=',$region_id)->get();
            return Response::json($warehouses);

        });
        Route::get('/information/create',function()
        {
            $cat_id = Input::get('category_id');
            $lines = \App\Line::where('category_id','=',$cat_id)->get();
            return Response::json($lines);

        });

        Route::get('/information/final',function()
        {
            $subcat_id = Input::get('subcategory_id');
            $finalcategories = \App\Finalcategory::where('subcategory_id','=',$subcat_id)->get();
            return Response::json($finalcategories);

        });
    });



});

Route::group(['middleware'=>['role:Специалисты']],function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');
Route::get('/tickets', 'HomeController@tickets')->name('tickets');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/forms', 'HomeController@forms')->name('forms');
Route::get('/tables', 'HomeController@tables')->name('tables');
Route::get('/buttons', 'HomeController@buttons')->name('buttons');
Route::get('/balance', 'HomeController@balance')->name('balance');
Route::get('/passages', 'HomeController@passages')->name('passages');
Route::get('/settings', 'HomeController@settings')->name('settings');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Session;


class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    //public function __construct() {
      //$this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
   // }


    public function index() {
        $user = \App\User::count();
        $equiptment = \App\Equiptment::count();

        $category = \App\Category::count();
        $warehouse = \App\Warehouse::count();
        $roles = Role::all();//Get all roles

        return view('admin.roles.index',[
            'user'=>$user,
            'equiptment'=>$equiptment,
            'category'=>$category,
            'warehouse'=>$warehouse,
            'roles'=>$roles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::all();//Get all permissions

        return view('admin.roles.create', ['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Validate name and permissions field
        $this->validate($request, [
                'name'=>'required|unique:roles|max:30',
                'permissions' =>'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
        //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail();
            //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first();
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role'. $role->name.' added!');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
        //Validate name and permission fields
        $this->validate($request, [
            'name'=>'required|max:10|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role'. $role->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
                'Role deleted!');

    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
                <h3><i class='fa fa-key'></i> Добавить Роль</h3>
            <hr>
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error  }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('roles.store') }}" method="post" >
                        @csrf
                        <div class="form-group">

                            <input type="text" name="name" class="form-control" placeholder="Название Роли" required>
                        </div>

            <h5><b>Привязать Права Доступа</b></h5>

            <div class='form-group'>
                <select class="form-control" name="permissions[]" multiple>
                @foreach ($permissions as $permission)

                    <option value="{{ $permission->id }}">{{ $permission->name }}</option>


                @endforeach
                </select>
            </div>

                        <button type="submit" class="btn btn-primary">Добавить Роль</button>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>
    @endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">


                <h3><i class='fa fa-key'></i> Редактировать Роль: {{$role->name}}</h3>
            <hr>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error  }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('roles.update',$role->id) }}" method="post">
                <input type="hidden" name="_method" value="PUT">
                @csrf
                <div class="form-group">
                    <label for="name">Название Роли</label>
                    <input type="text" value="{{$role->name}}" class="form-control" id="name"  name="name" >
                </div>

            <h5><b>Assign Permissions</b></h5>
            <select class="form-control" name="permissions[]" multiple>
                @foreach ($permissions as $permission)

                    <option value="{{ $permission->id }}">{{ $permission->name }}</option>


                @endforeach
            </select>
            <br>
                <button type="submit" class="btn btn-primary">Редактировать</button>

            </form>
        </div>

    @endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <!-- page content -->
        <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-user"></i> Кол-во Пользователей</span>
                <div class="count">{{ $user}}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во оборудования</span>
                <div class="count">{{ $equiptment }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во складов</span>
                <div class="count">{{ $warehouse }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во категорий</span>
                <div class="count">{{ $category }}</div>
            </div>



        </div>

        <div class="col-lg-10 col-lg-offset-1">

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <h2><i class="fa fa-key"></i> Роли  <a href="{{ route('users.index') }}" class="btn btn-primary pull-right">Пользователи</a>
                            <a href="{{ route('permissions.index') }}" class="btn btn-success pull-right">Права доступа</a></h2>
                        <hr>
                        <div class="x_content">

                            <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Роль</th>
                        <th>Права доступа</th>
                        <th>Действия</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($roles as $role)
                        <tr>

                            <td>{{ $role->name }}</td>

                            <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}

                            <td>
                                <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-sm btn-success-outline"  style="margin-right: 3px;"><i class="fa fa-edit"  aria-hidden="true"></i></a>


                                <form action="{{ route('roles.destroy', $role->id) }}" method="post" >
                                    {{method_field('DELETE')}}
                                    @csrf
                                    <button type="submit" style="border: 0; background: none;margin-left: 5px;" data-toggle="tooltip" data-original-title="Delete"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>
                            <a href="{{ route('roles.create') }}" class="btn btn-success">Создать Роль</a>
            </div>
                            </div>

                        </div>
                    </div>
                </div>

    </div>
    @endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.app_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2> Show Role</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    {{ $role->name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Permissions:</strong>
                    @if(!empty($rolePermissions))
                        @foreach($rolePermissions as $v)
                            <label class="label label-success">{{ $v->name }},</label>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
    @endsection