routes/web.php
<?php
use Illuminate\Support\Facades\Input;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
   // return view('welcome');
//});

Route::get('/', '\App\Http\Controllers\Auth\LoginController@showLoginForm');
Auth::routes();


Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware' => ['auth']], function(){
    Route::group(['middleware'=>['role:Администратор|Заведующий Складом']],function(){

    Route::get('/reports',[
        'as'=>'reports.index',
        'uses'=>'ReportController@index'
    ]);
        Route::get('logout/', 'DashboardController@logout')->name('admin.logout');
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
        //Route::get('profile', 'DashboardController@profile')->name('profile');
        Route::post('/stocks/{id}',[
            'as' => 'stocks.add',
            'uses' => 'StockController@add'
        ]);


        Route::resource('stocks','StockController');
        Route::resource('finalcategories','FinalcategoryController');
        Route::resource('lines','LineController');
        Route::resource('equiptments', 'EquiptmentController');
        Route::resource('equiptstatuses', 'EquiptstatusController');
        Route::resource('subcategories','SubcategoryController');
        Route::resource('categories','CategoryController');
        Route::resource('regions','RegionController');
        Route::resource('departments','DepartmentController');
        Route::resource('tollings','TollingController');
        Route::resource('roles','RoleController');
        Route::resource('warehouses','WarehouseController');
        Route::resource('users','UserController');
        Route::resource('permissions', 'PermissionController');



        Route::get('/information/create/ajax-state',function()
        {
            $cat_id = Input::get('category_id');
            $subcategories = \App\Subcategory::where('category_id','=',$cat_id)->get();
            return Response::json($subcategories);

        });

        Route::get('/information/create/ajax',function()
        {
            $region_id = Input::get('region_id');
            $warehouses = \App\Warehouse::where('region_id','=',$region_id)->get();
            return Response::json($warehouses);

        });
        Route::get('/information/create',function()
        {
            $cat_id = Input::get('category_id');
            $lines = \App\Line::where('category_id','=',$cat_id)->get();
            return Response::json($lines);

        });

        Route::get('/information/final',function()
        {
            $subcat_id = Input::get('subcategory_id');
            $finalcategories = \App\Finalcategory::where('subcategory_id','=',$subcat_id)->get();
            return Response::json($finalcategories);

        });
    });



});

Route::group(['middleware'=>['role:Специалисты']],function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');
Route::get('/tickets', 'HomeController@tickets')->name('tickets');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/forms', 'HomeController@forms')->name('forms');
Route::get('/tables', 'HomeController@tables')->name('tables');
Route::get('/buttons', 'HomeController@buttons')->name('buttons');
Route::get('/balance', 'HomeController@balance')->name('balance');
Route::get('/passages', 'HomeController@passages')->name('passages');
Route::get('/settings', 'HomeController@settings')->name('settings');
});

resources/views/admin/warehouses/create.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-institution'></i> Добавить Склад</h3>
        <br>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('warehouses.store') }}" method="post" >
            @csrf

            <div class="form-group">
                <label for="name">Название Склада</label>
                <input type="text" name="name" class="form-control" placeholder="Название склада" required>
            </div><br>
            <div class="form-group">
                <label for="name">Регион</label>
                <select class="form-control" name="region_id" id="region">
                    @foreach($regions as $region)
                        <option value="{{$region->id}}">{{ $region->name }}</option>
                    @endforeach
                </select>
            </div><br>
            <button type="submit" class="btn btn-primary">Добавить</button>

        </form>
    </div>


@endsection

resources/views/admin/warehouses/edit.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-institution'></i> Редактировать Cклад</h3>
        <br>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('warehouses.update', $warehouse->id) }}" method="post" >
            <input type="hidden" name="_method" value="PUT">
            @csrf

            <div class="form-group">
                <label for="name">Название Склада</label>
                <input type="text" name="name" class="form-control" value="{{$warehouse->name}}" placeholder="Название" required>
            </div><br>
            <div class="form-group">
                <label for="name">Регион</label>
                <select class="form-control" name="region_id" id="region">
                    @foreach($regions as $region)
                        <option value="{{$region->id}}" {{ $region->id == $warehouse->region_id ? "selected" : "" }}>{{ $region->name }}</option>
                    @endforeach
                </select>
            </div><br>
            <button type="submit" class="btn btn-primary">Изменить</button>


        </form>
    </div>


@endsection

resources/views/admin/warehouses/index.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <!-- page content -->
        <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-user"></i> Кол-во Пользователей</span>
                <div class="count">{{ $user}}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во оборудования</span>
                <div class="count">{{ $equiptment }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во складов</span>
                <div class="count">{{ $warehouse }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во категорий</span>
                <div class="count">{{ $category }}</div>
            </div>



        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <h2><i class="fa fa-institution"></i> Список складов </h2>
                    <hr>
                    <div class="x_content">

                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Название</th>
                                <th>Дата</th>
                                <th>Действия</th>
                            </tr>
                            </thead>


                            <tbody>
                            @foreach ($warehouses as $warehouse)
                                <tr>
                                    <td>{{ $warehouse->id }}</td>
                                    <td> <a href="{{ route('warehouses.show', $warehouse->id) }}">{{$warehouse->name }}</a></td>
                                    <?php
                                    setlocale(LC_ALL, 'ru_RU.UTF-8');
                                    ?>
                                    <td>{{ $warehouse->created_at->formatLocalized('%d %B %Y, %I:%M:%S %p') }}</td>
                                    {{-- Retrieve array of roles associated to a user and convert to string --}}
                                    <td>
                                        <a href="{{ route('warehouses.show', $warehouse->id) }}" class="btn btn-success"  style="margin-right: 3px;">Подробнее</a>
                                        <a href="{{ route('warehouses.edit', $warehouse->id) }}" class="btn btn-primary"  style="margin-right: 3px;">Редактировать</a>


                                        <form action="{{ route('warehouses.destroy', $warehouse->id) }}" method="post" class="btn-group inline">
                                            {{method_field('DELETE')}}
                                            @csrf
                                            <button type="submit" class="btn btn-danger" style="position: relative;bottom:2px">Удалить</button>
                                        </form>

                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                    <a href="{{ route('warehouses.create') }}" class="btn btn-success">Создать Склад</a>
                </div>

            </div>

        </div>
    </div>
@endsection

resources/views/admin/warehouses/show.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-car'></i> {{ $warehouse->name }}</h3>
        <br>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


            <div class="form-group">
                <label for="name">Название Склада</label>
                <input type="text" name="name" class="form-control" value="{{$warehouse->name}}" placeholder="Название" disabled>
            </div><br>
            <div class="form-group">
                <label for="name">Регион</label>
                <select class="form-control" name="region_id" id="region" disabled>
                    @foreach($regions as $region)
                        <option value="{{$region->id}}" {{ $region->id == $warehouse->region_id ? "selected" : "" }}>{{ $region->name }}</option>
                    @endforeach
                </select>
            </div><br>


    </div>


@endsection