routes/web.php
<?php
use Illuminate\Support\Facades\Input;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
   // return view('welcome');
//});

Route::get('/', '\App\Http\Controllers\Auth\LoginController@showLoginForm');
Auth::routes();


Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware' => ['auth']], function(){
    Route::group(['middleware'=>['role:Администратор|Заведующий Складом']],function(){

    Route::get('/reports',[
        'as'=>'reports.index',
        'uses'=>'ReportController@index'
    ]);
        Route::get('logout/', 'DashboardController@logout')->name('admin.logout');
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
        //Route::get('profile', 'DashboardController@profile')->name('profile');
        Route::post('/stocks/{id}',[
            'as' => 'stocks.add',
            'uses' => 'StockController@add'
        ]);


        Route::resource('stocks','StockController');
        Route::resource('finalcategories','FinalcategoryController');
        Route::resource('lines','LineController');
        Route::resource('equiptments', 'EquiptmentController');
        Route::resource('equiptstatuses', 'EquiptstatusController');
        Route::resource('subcategories','SubcategoryController');
        Route::resource('categories','CategoryController');
        Route::resource('regions','RegionController');
        Route::resource('departments','DepartmentController');
        Route::resource('tollings','TollingController');
        Route::resource('roles','RoleController');
        Route::resource('warehouses','WarehouseController');
        Route::resource('users','UserController');
        Route::resource('permissions', 'PermissionController');



        Route::get('/information/create/ajax-state',function()
        {
            $cat_id = Input::get('category_id');
            $subcategories = \App\Subcategory::where('category_id','=',$cat_id)->get();
            return Response::json($subcategories);

        });

        Route::get('/information/create/ajax',function()
        {
            $region_id = Input::get('region_id');
            $warehouses = \App\Warehouse::where('region_id','=',$region_id)->get();
            return Response::json($warehouses);

        });
        Route::get('/information/create',function()
        {
            $cat_id = Input::get('category_id');
            $lines = \App\Line::where('category_id','=',$cat_id)->get();
            return Response::json($lines);

        });

        Route::get('/information/final',function()
        {
            $subcat_id = Input::get('subcategory_id');
            $finalcategories = \App\Finalcategory::where('subcategory_id','=',$subcat_id)->get();
            return Response::json($finalcategories);

        });
    });



});

Route::group(['middleware'=>['role:Специалисты']],function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');
Route::get('/tickets', 'HomeController@tickets')->name('tickets');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/forms', 'HomeController@forms')->name('forms');
Route::get('/tables', 'HomeController@tables')->name('tables');
Route::get('/buttons', 'HomeController@buttons')->name('buttons');
Route::get('/balance', 'HomeController@balance')->name('balance');
Route::get('/passages', 'HomeController@passages')->name('passages');
Route::get('/settings', 'HomeController@settings')->name('settings');
});

app/Finalcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Finalcategory extends Model
{
    protected $fillable = ['id', 'name', 'subcategory_id'];
    public function subcategories()
    {
        return $this->belongsTo('App\Subcategory');
    }
}

app/Http/Controllers/Admin/FinalcategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Finalcategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Subcategory;

class FinalcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = Subcategory::orderBy('id','asc')->get();
        $finalcategories = Finalcategory::all();
        $user = \App\User::count();
        $equiptment = \App\Equiptment::count();
        $category = \App\Category::count();
        $warehouse = \App\Warehouse::count();
        return view('admin.finalcategories.index', [
            'subcategories'=>$subcategories,
            'finalcategories'=>$finalcategories,
            'user'=>$user,
            'equiptment'=>$equiptment,
            'category'=>$category,
            'warehouse'=>$warehouse
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.finalcategories.create',[
            'finalcategory'=>[],
            'subcategories'=>Subcategory::orderBy('id','asc')->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=> 'required|max:255',
            'subcategory_id'=>'required|integer',
        ]);
        $finalcategory = new Finalcategory();
        $finalcategory->name = $request['name'];
        $finalcategory->subcategory_id = $request['subcategory_id'];
        $finalcategory->save();
        return redirect()->route('finalcategories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $finalcategory = Finalcategory::findOrFail($id);
        return view('admin.finalcategories.show', [
            'finalcategory'=>$finalcategory,
            'subcategories'=>Subcategory::orderBy('id','asc')->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $finalcategory = Finalcategory::findOrFail($id);
        return view('admin.finalcategories.edit', [
            'finalcategory'=>$finalcategory,
            'subcategories'=>Subcategory::orderBy('id','asc')->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $finalcategory = Finalcategory::findOrFail($id);
        $this->validate($request,[
            'name'=> 'required|max:255',
            'subcategory_id'=>'required|integer',
        ]);

        $finalcategory->name = $request['name'];
        $finalcategory->subcategory_id = $request['subcategory_id'];
        $finalcategory->save();
        return redirect()->route('finalcategories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $finalcategory = Finalcategory::findOrFail($id);
        $finalcategory->delete();
        return redirect()->route('finalcategories.index');
    }
}

resources/views/admin/finalcategories/create.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-folder-o'></i> Добавить Финальную категорию</h3>
        <br>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('finalcategories.store') }}" method="post" >
            @csrf
            <div class="form-group">
                <label>Подкатегория</label>
                <select class="form-control" name="subcategory_id" id="subcategory">
                    <option>Выбрать под категорию</option>
                    @foreach($subcategories as $subcategory)

                        <option value="{{$subcategory->id}}">{{ $subcategory->name }}</option>
                    @endforeach
                </select>
            </div>
            <!--<div class="form-group">
                <label>Подкатегории
                    <select class="form-control" name="subcategory" id="subcategory">
                        <option value=""></option>
                    </select>
                </label>
            </div>-->
            <div class="form-group">
                <label for="name">Название Финальной категории</label>
                <input type="text" name="name" class="form-control" placeholder="Название категории" required>
            </div><br>
            <button type="submit" class="btn btn-primary">Добавить</button>

        </form>
    </div>
    <script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('#subcategory').select2({
            closeOnSelect: true
        });


    </script>
    <!--<script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script>
        $('#category').on('change', function(e){
            console.log(e);
            var cat_id = e.target.value;

            $.get('{{ url('admin/information') }}/create/ajax-state?category_id=' + cat_id, function(data) {
                //console.log(data);
                $('#subcategory').empty();
                $.each(data, function(index,subCatObj){
                    //console.log(subCatObj.name);
                    $('#subcategory').append('<option value="'+subCatObj.id+'">'+subCatObj.name+'</option>')
                });

            });
        });
    </script>-->

@endsection

resources/views/admin/finalcategories/edit.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-folder-o'></i> Добавить Финальную категорию</h3>
        <br>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error  }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('finalcategories.update',$finalcategory->id) }}" method="post" >
            <input type="hidden" name="_method" value="PUT">
            @csrf
            <div class="form-group">
                <label>Подкатегория</label>
                <select class="form-control" name="subcategory_id" id="subcategory">
                    @foreach($subcategories as $subcategory)

                        <option value="{{$subcategory->id}}" {{ $subcategory->id == $finalcategory->subcategory_id ? "selected" : "" }}>{{ $subcategory->name }}</option>
                    @endforeach
                </select>
            </div>
            <!--<div class="form-group">
                <label>Подкатегории
                    <select class="form-control" name="subcategory" id="subcategory">
                        <option value=""></option>
                    </select>
                </label>
            </div>-->
            <div class="form-group">
                <label for="name">Название Финальной категории</label>
                <input type="text" name="name" class="form-control" placeholder="Название категории" value="{{ $finalcategory->name }}" required>
            </div><br>
            <button type="submit" class="btn btn-primary">Изменить</button>

        </form>
    </div>
    <script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('#subcategory').select2({
            closeOnSelect: true
        });


    </script>
    <!--<script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script>
        $('#category').on('change', function(e){
            console.log(e);
            var cat_id = e.target.value;

            $.get('{{ url('admin/information') }}/create/ajax-state?category_id=' + cat_id, function(data) {
                //console.log(data);
                $('#subcategory').empty();
                $.each(data, function(index,subCatObj){
                    //console.log(subCatObj.name);
                    $('#subcategory').append('<option value="'+subCatObj.id+'">'+subCatObj.name+'</option>')
                });

            });
        });
    </script>-->

@endsection

resources/views/admin/finalcategories/index.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <!-- page content -->
        <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-user"></i> Кол-во Пользователей</span>
                <div class="count">{{ $user}}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во оборудования</span>
                <div class="count">{{ $equiptment }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во складов</span>
                <div class="count">{{ $warehouse }}</div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                <span class="count_top"><i class="fa fa-desktop"></i> Кол-во категорий</span>
                <div class="count">{{ $category }}</div>
            </div>



        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <h2><i class="fa fa-folder-o"></i> Финальная категория </h2>
                    <hr>
                    <div class="x_content">

                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Дата</th>
                                <th>Действия</th>
                            </tr>
                            </thead>


                            <tbody>

                            @foreach($finalcategories as $finalcategory)
                                <tr>
                                    <td> <a href="{{ route('finalcategories.show',$finalcategory->id) }}">{{$finalcategory->name }}</a></td>
                                    <?php
                                    setlocale(LC_ALL, 'ru_RU.UTF-8');
                                    ?>
                                    <td>{{ $finalcategory->created_at->formatLocalized('%d %B %Y, %I:%M:%S %p') }}</td>
                                    {{-- Retrieve array of roles associated to a user and convert to string --}}
                                    <td>
                                        <a href="{{ route('finalcategories.show', $finalcategory->id) }}" class="btn btn-success"  style="margin-right: 3px;">Подробнее</a>
                                        <a href="{{ route('finalcategories.edit', $finalcategory->id) }}" class="btn btn-primary"  style="margin-right: 3px;">Редактировать</a>


                                        <form action="{{ route('finalcategories.destroy', $finalcategory->id) }}" method="post" class="btn-group inline">
                                            {{method_field('DELETE')}}
                                            @csrf
                                            <button type="submit" class="btn btn-danger" style="position: relative;bottom:2px">Удалить</button>
                                        </form>

                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                    <a href="{{ route('finalcategories.create') }}" class="btn btn-success">Создать Финальную категорию</a>
                </div>

            </div>

        </div>
    </div>
@endsection

resources/views/admin/finalcategories/show.blade.php
@extends('layouts.app_header_admin')
<!-- Content Wrapper. Contains page content -->
@section('content')
    <div class="right_col" role="main">
        <h3><i class='fa fa-folder-o'></i> {{ $finalcategory->name }}</h3>
        <br>


        <div class="form-group">
            <label>Подкатегория</label>
            <select class="form-control" name="subcategory_id" id="subcategory" disabled>
                <!--<option value=""></option>-->
                @foreach($subcategories as $subcategory)

                    <option value="{{$subcategory->id}}" {{ $subcategory->id == $finalcategory->subcategory_id ? "selected" : "" }}>{{ $subcategory->name }}</option>

                @endforeach
            </select>
        </div>
        <!--<div class="form-group">
            <label>Подкатегории
                <select class="form-control" name="subcategory" id="subcategory">
                    <option value=""></option>
                </select>
            </label>
        </div>-->
        <div class="form-group">
            <label for="name">Название Финальной категории</label>
            <input type="text" name="name" value="{{ $finalcategory->name }}" class="form-control" placeholder="Название категории" disabled>
        </div><br>

    </div>
    <!-- <script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script>
        $('#category').on('change', function(e){
            console.log(e);
            var cat_id = e.target.value;

            $.get('{{ url('admin/information') }}/create/ajax-state?category_id=' + cat_id, function(data) {
                //console.log(data);
                $('#subcategory').empty();
                $.each(data, function(index,subCatObj){
                    //console.log(subCatObj.name);
                    $('#subcategory').append('<option value="'+subCatObj.id+'">'+subCatObj.name+'</option>')
                });

            });
        });
    </script>-->

@endsection